# Generated by Django 2.0.1 on 2018-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('birthDate', models.DateTimeField(verbose_name='date published')),
                ('objective', models.CharField(max_length=1000)),
                ('whatIDo', models.CharField(max_length=1000)),
            ],
        ),
    ]
