# Generated by Django 2.0.1 on 2018-01-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffesion', models.CharField(max_length=100)),
                ('someIntro', models.CharField(max_length=300)),
            ],
        ),
    ]
