# Generated by Django 2.0.1 on 2018-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_name', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('time_required', models.CharField(max_length=3)),
            ],
        ),
    ]
