# Generated by Django 2.0.1 on 2018-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='birthDate',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resign_date',
            field=models.DateField(),
        ),
    ]
